### ISSUE TITLE
RCCL ignores AMDGPU_TARGETS and builds for all hardcoded arches anyway

### ISSUE THREAD

**Issue by AngryLoki** [ROCm/rccl#958]
Hi, while updating build script for rccl-5.7.1 in Gentoo, I noticed that RCCL ignores `-DAMDGPU_TARGETS=...` parameter, which makes compilation for a single GPU significantly slower than it could be.

AMDGPU_TARGETS works for every ROCm package I checked (miopen, hipCUB, rocBLAS, hipRAND, rocFFT, and so on), the only difference, why it does not work in rccl is because it uses `FORCE` in `set(AMDGPU_TARGETS` definition:
https://github.com/ROCmSoftwarePlatform/rccl/blob/rocm-5.7.1/CMakeLists.txt#L65

Can you remove this `FORCE` in some future release? Thanks!

**Comment by nileshnegi** [comment]
Fixed in https://github.com/ROCm/rccl/commit/414884c6cbc18f40c880d9b7bed39132e9f349fa
